# To update pre-commit configuration:
# Open anaconda terminal
# Go to repository root dir, where .pre-commit-config.yaml is located
# Execute: pre-commit install
# (Optional) Test new configuration by executing: pre-commit run --all-files

default_language_version:
    python: python3.10
exclude: '^$'
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast  # Is it valid Python?
        types: [python]
    -   id: debug-statements  # Check for debugger imports and py37+ breakpoint() calls in python source.
    # -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        types: [text, python]
        fail_fast: false
    -   id: check-docstring-first
        types: [python]
    -   id: end-of-file-fixer
        types: [python]
        fail_fast: false
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        types: [python]
        fail_fast: false
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
    -   id: isort
        fail_fast: false
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        stages: [push]
        types: [python]
        entry: pytest  # maybe need to cd into correct dir? see https://stackoverflow.com/questions/63232136/how-to-run-pre-commit-on-separate-folders
        language: system
        pass_filenames: false
        always_run: false
        fail_fast: false
        verbose: true
        log_file: git_pytest_.log