# To update pre-commit configuration:
# Open anaconda terminal
# Go to repository root dir, where .pre-commit-config.yaml is located
# Execute: pre-commit install
# (Optional) Test new configuration by executing: pre-commit run --all-files

default_install_hook_types: [pre-commit, pre-push]
default_stages: [commit, push]
default_language_version:
    python: python3.10
exclude: '^$'
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast  # Is it valid Python?
        types: [python]
    -   id: debug-statements  # Check for debugger imports and py37+ breakpoint() calls in python source.
    # -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        types: [text, python]
    -   id: check-docstring-first
        types: [python]
    -   id: end-of-file-fixer
        types: [python]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        types: [python]
#
# pytest does not use the correct environment
#-   repo: local
#    hooks:
#    -   id: pytest-check
#        name: pytest-check
#        stages: [push]
#        types: [python]
#        files: \.py$
#        language: system
#        entry: C:/Users/Johannes/anaconda3/Scripts/pytest.exe ./tests/ --cov=./ --cov-fail-under=50
#        pass_filenames: false
#        always_run: false
#        fail_fast: false
#        verbose: true